---
abstract: 'Interface to Bzip2 compression library'
author:
  - 'Rob Janes <arjay@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Compress-Bzip2
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Config: 0
  Fcntl: 0
  File::Copy: 0
  File::Spec: 0
  Getopt::Std: 0
  Test::More: 0
version: 2.10
